#ifndef __VXLLOGAUX_H__
#define __VXLLOGAUX_H__

enum VXL_LOG_LEVEL
{
    VXL_LOG_LEVEL_INVALID = -1,
    VXL_LOG_TRACE = 0,
    VXL_LOG_INFO,
    VXL_LOG_WARNING,
    VXL_LOG_ERROR,
    VXL_LOG_FATAL,
    VXL_LOG_NONE,
    VXL_LOG_LEVEL_COUNT,
    VXL_LOG_LEVEL_DEFAULT = VXL_LOG_WARNING
};

#endif
