// ================================================================
// Copyright (c) 2019-2023 by VX-Lab. All rights reserved.
// 
// This file is property of VX-Lab. Any unauthorized copy,
// use or distribution is an offensive act against international
// law and may be prosecuted under federal law. Its content is
// company confidential asset.
// ================================================================
#ifndef _IVIDEOCAPAUX_H_ //auto generated by vim script
#define _IVIDEOCAPAUX_H_

#include "vxlComTypes.h"

typedef struct _VideoCapCfg
{
    unsigned int    chnId;          // channel id
    double          fps;            // input frame rate
    double          capFocus;       // focus of the camera(-1.0, auto_focus; > 1.0, set the actual value)
    VxlSize         capSize;        // resolution of the capture
    bool            bShowDetails;   // flag for showing details if needed
    bool            bRecDetails;    // flag for recording details if needed

    _VideoCapCfg()
    {
        chnId           = 0;
        fps             = 0.0;
        capFocus        = -1.0;
        capSize         = VxlSize(640, 480);
        bShowDetails    = false;
        bRecDetails     = false;
    }
} VideoCapCfg;

typedef struct _VideoCapPara
{
    double          capFocus;       // focus of the camera(-1.0, auto_focus; > 1.0, set the actual value)
    _VideoCapPara()
    {
        capFocus = -1.0;
    }
} VideoCapPara;


#endif //_IVIDEOCAPAUX_H_
